# Generated by Django 2.2.28 on 2024-03-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperatureApparent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.CharField(max_length=50, null=True)),
                ('wind_direction', models.CharField(max_length=50, null=True)),
                ('conditions', models.CharField(max_length=100, null=True)),
                ('weatherDescription', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('uvIndex', models.IntegerField(null=True)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dewPoint', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ceiling', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cloudCover', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('windGust', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Location')),
            ],
        ),
    ]
